### ISSUE TITLE
is it accurate enough to detect the inputs and outputs of a store?

### ISSUE THREAD

**Issue by lakano** [vramosx/react-native-expo-geofence#1]
Hi,
We surely need to uses an ibeacon/eddystone for that, but we would like to known if the geofence is enough precise to detect when someone come inside a shop and go out of the shop.
Do you believe it's enough precise please?
Regards,

**Comment by vramosx** [comment]
Hi @lakano,

The library only calculates the distance between the points, turning them into km. The accuracy depends on the device and the signal.

Cheers,
